services:
  api:
    build:
      context: .
      dockerfile: Company.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - POSTGRES_DB=CompanyServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - AUTH_AUTHORITY=http://company-auth:5000
    depends_on:
      postgres:
        condition: service_healthy
      company-auth:
        condition: service_started
    networks:
      - company-network
    command: ["sh", "-c", "./wait-for-it.sh postgres:5432 -- dotnet Company.Api.dll"]

  company-auth:
    build:
      context: ./Company.Auth
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - company-network

  postgres:
    image: postgres:latest
    container_name: company-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=CompanyServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - company-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # Frontend Angular Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: company-client
    ports:
      - "4200:80"
    depends_on:
      - api
      - company-auth
    networks:
      - company-network
      
  # Test Service
  company-tests:
    build:
      context: .
      dockerfile: Company.Tests/Dockerfile
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Test
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
      company-auth:
        condition: service_started
    networks:
      - company-network

networks:
  company-network:
    driver: bridge

volumes:
  postgres-data: 